openapi: 3.0.2
info:
  description: Linkwarden API Documentation
  version: 1.0.0
  title: Linkwarden API
  license:
    name: GNU Affero General Public License v3.0
    url: "https://www.gnu.org/licenses/agpl-3.0.html"
tags:
  - name: Archives
  - name: Auth
  - name: Avatar
  - name: Collections
  - name: Dashboard
  - name: Links
  - name: Logins
  - name: Migration
  - name: Public
  - name: Session
  - name: Tags
  - name: Tokens
  - name: Users
paths:
  /api/v1/archives/{linkId}:
    post:
      tags:
        - Archives
      summary: Uploads a file to an archive by link ID
      parameters:
        - $ref: "#/components/parameters/LinkIdParameter"
        - name: format
          in: query
          required: true
          description: "The numeric value corresponding to the format of the file being uploaded: 0 = PNG, 1 = JPEG, 2 = PDF."
          schema:
            type: integer
            enum:
              - 0 # PNG
              - 1 # JPEG
              - 2 # PDF
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/UploadFile"
      responses:
        "200":
          $ref: "#/components/responses/UploadSuccess"
        "400":
          $ref: "#/components/responses/BadRequest"
      security:
        - bearerAuth: []
      description: Uploads a file to the specified archive. Supports PDF, PNG, and JPEG formats.
    get:
      tags:
        - Archives
      summary: Retrieves an archive file by link ID
      parameters:
        - $ref: "#/components/parameters/LinkIdParameter"
        - name: format
          in: query
          required: false
          description: >
            The numeric value corresponding to the desired archive format:
            0 = PNG, 1 = JPEG, 2 = PDF, 3 = Readability JSON, 4 = Monolith HTML.
          schema:
            type: integer
            enum:
              - 0 # PNG
              - 1 # JPEG
              - 2 # PDF
              - 3 # Readability JSON
              - 4 # Monolith HTML
        - name: preview
          in: query
          required: false
          description: Indicates whether to return a preview of the archive.
          schema:
            type: boolean
      responses:
        "200":
          $ref: "#/components/responses/GetArchiveSuccess"
        "404":
          $ref: "#/components/responses/FileNotFound"
      security:
        - bearerAuth: []
      description: Retrieves an archive file in the specified format.
    put:
      tags:
        - Archives
      summary: Updates an archive file by link ID
      parameters:
        - $ref: "#/components/parameters/LinkIdParameter"
        - name: format
          in: query
          required: false
          description: >
            The numeric value corresponding to the desired archive format:
            0 = PNG, 1 = JPEG, 2 = PDF, 3 = Readability JSON, 4 = Monolith HTML.
          schema:
            type: integer
            enum:
              - 0 # PNG
              - 1 # JPEG
              - 2 # PDF
              - 3 # Readability JSON
              - 4 # Monolith HTML
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/UploadFile"
      responses:
        "200":
          description: Archive file successfully updated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: object
                    description: Updated details of the archive.
        "400":
          description: Bad Request - Invalid file type, file too large, or permission issues.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: The error message describing why the request failed.
      security:
        - bearerAuth: []
      description: Updates an archive file by replacing the existing file. Supports PDF, PNG, and JPEG formats.
  /api/v1/auth/forgot-password:
    post:
      tags:
        - Auth
      summary: Sends a password reset email to the user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ForgotPasswordSchema"
      responses:
        "200":
          description: Password reset email sent successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    example: "Password reset email sent."
        "400":
          description: Invalid request or too many password reset requests.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    example: "Too many requests. Please try again later."
        "404":
          description: User not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    example: "No user found with that email."
  /api/v1/auth/reset-password:
    post:
      tags:
        - Auth
      summary: Resets the password for a user using a valid token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResetPasswordSchema"
      responses:
        "200":
          description: Password has been reset successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    example: "Password has been reset successfully."
        "400":
          description: Invalid token or error during password reset.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    example: "Invalid token."
  /api/v1/auth/verify-email:
    post:
      tags:
        - Auth
      summary: Verifies the user's email after they click a verification link
      parameters:
        - name: token
          in: query
          required: true
          description: The verification token sent to the user's email.
          schema:
            type: string
      responses:
        "200":
          description: Email verification successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    example: "Email verified successfully."
        "400":
          description: Invalid token or email already in use.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    example: "Invalid token."
  /api/v1/avatar/{id}:
    get:
      tags:
        - Avatar
      summary: Retrieves the avatar of a user by their ID
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user whose avatar is to be retrieved.
          schema:
            type: integer
      responses:
        "200":
          description: Avatar image successfully retrieved
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
        "400":
          description: File inaccessible or invalid parameters
          content:
            text/plain:
              schema:
                type: string
                example: "File inaccessible."
        "401":
          description: Invalid parameters
          content:
            text/plain:
              schema:
                type: string
                example: "Invalid parameters."
      security:
        - bearerAuth: []
      description: Retrieves the avatar for a user identified by their ID.

components:
  parameters:
    LinkIdParameter:
      name: linkId
      in: path
      required: true
      description: The ID of the desired link
      schema:
        type: string
  schemas:
    UploadFile:
      type: object
      properties:
        file:
          type: string
          format: binary
          description: The file to upload (PNG, JPEG, or PDF).
      required:
        - file
    ForgotPasswordSchema:
      type: object
      properties:
        email:
          type: string
          format: email
          description: The email of the user requesting the password reset.
      required:
        - email
    ResetPasswordSchema:
      type: object
      properties:
        token:
          type: string
          description: The password reset token.
        password:
          type: string
          minLength: 8
          description: The new password to set.
      required:
        - token
        - password
  responses:
    UploadSuccess:
      description: File successfully uploaded and processed.
      content:
        application/json:
          schema:
            type: object
            properties:
              response:
                type: object
                description: Details about the uploaded file.
    BadRequest:
      description: Bad Request - Invalid file type, file too large, or permission issues.
      content:
        application/json:
          schema:
            type: object
            properties:
              response:
                type: string
                description: The error message describing why the request failed.
    GetArchiveSuccess:
      description: Archive file retrieved successfully.
      content:
        application/json:
          schema:
            type: object
            properties:
              response:
                type: object
                description: The archive file.
    FileNotFound:
      description: The requested archive file was not found.
      content:
        application/json:
          schema:
            type: object
            properties:
              response:
                type: string
                example: "File not found."
